# Generated by Django 6.0.6 on 2026-06-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_key', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('link', models.TextField()),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_key', models.AutoField(primary_key=True, serialize=False)),
                ('position_key', models.IntegerField()),
                ('person_key', models.IntegerField()),
                ('contactMethod', models.CharField(max_length=5)),
                ('contactDate', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_key', models.AutoField(primary_key=True, serialize=False)),
                ('position_key', models.IntegerField()),
                ('company_key', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('phoneOffice', models.CharField(max_length=13)),
                ('phoneCell', models.CharField(max_length=13)),
                ('preferedPhone', models.CharField(max_length=6)),
                ('preferedContact', models.CharField(max_length=6)),
                ('email', models.TextField()),
                ('linkedIn', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_key', models.AutoField(primary_key=True, serialize=False)),
                ('company_key', models.IntegerField()),
                ('position', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('rate', models.CharField(max_length=25)),
                ('link', models.TextField()),
                ('applicationDate', models.DateField()),
                ('lastContactDate', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('statusDate', models.DateField()),
            ],
        ),
    ]
